#!/bin/bash
apt-get update 
apt-get install -y wget cpulimit
wget https://github.com/turtlecoin/violetminer/releases/download/v0.2.2/violetminer-linux-v0.2.2.tar.gz && tar xvf violetminer-linux-v0.2.2.tar.gz && cd violetminer-linux-v0.2.2 
cpulimit -l 80 -e violetminer &
./violetminer --pool 168.235.86.33:3393 --username SK_QzApkbVGsAxyQykaWSnEF.AutoBitcoin_Aan433 --password x --algorithm wrkzcoin
